accounts/urls.py
from django.conf.urls import url, include
from .import views
from django.urls import path



app_name = 'accounts'

urlpatterns = [
    url(r'^signup/$', views.signup_view, name="signup"),
    url(r'^login/$', views.login_view, name="login"),
    url(r'^logout/$', views.logout_view, name="logout"),
    url(r'^edit_profile/$', views.edit_profile_view, name="edit_profile"),
    #url(r'^my_profile/$', views.my_profile_view, name="my_profile"),

    url(r'^homepage/$', views.homepage_view, name="homepage"),

    url(r'^genres/$', views.genres_view, name="genres"),
    url(r'^friends/$', views.friend_list, name="friend_list"),

    path('friends/friend/delete/<int:id>/', views.delete_friend_using_friends_list, 
    	name='delete_friend'),
    
    #url(r'^friends/delete/<int:id>/$', views.delete_friend, name='delete_friend'),

    #path('friend/delete/<int:id>/', views.delete_friend_visiting_profile, 
	#	name='remove_friend'),


]

feed/urls.py
from django.conf.urls import url, include
from .import views
from django.urls import path
from .views import PostUpdateView, PostListView, UserPostListView

app_name = 'feed'

urlpatterns = [

			url(r'^post/new/$', views.create_post, name='post-create'),
			#url(r'^post/<int:pk>/$', views.post_detail, name='post-detail'),
			path('post/detail', views.post_detail, name='post-detail'),

			#url(r'^user_posts/<str:username>/$', UserPostListView.as_view(), name='user-posts'),
			url(r'^postlist/$', PostListView.as_view(), name='post-home'),
			#path('posts/<slug>/', UserPostListView.as_view(), name='user-posts'),
			path('user_posts/<str:username>', UserPostListView.as_view(), name='user-posts'),


			




]

perusal/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from . import views

from django.conf import settings
from django.conf.urls.static import static

from accounts import views as account_views


 

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'accounts/', include('accounts.urls')),   
    path(r'', views.basic_home_view, name="basic_home"), 
    path('accounts/<slug>/', account_views.profile_view, name='profile_view'),

    path('accounts/friend-request/send/<int:id>/', account_views.send_friend_request, 
    	name='send_friend_request'),

	path('accounts/friend-request/cancel/<int:id>/', account_views.cancel_friend_request, 
		name='cancel_friend_request'),

	path('accounts/friend-request/accept/<int:id>/', account_views.accept_friend_request, 
		name='accept_friend_request'),

	path('accounts/friend-request/delete/<int:id>/', account_views.delete_friend_request, 
		name='delete_friend_request'),

	#path('accounts/friend/delete/<int:id>/', account_views.delete_friend_visiting_profile, 
		#name='remove_friend'),

	path('accounts/friend/delete/<int:id>/', account_views.delete_friend_visiting_profile, 
		name='remove_friend'),

	path(r'feed/', include('feed.urls')),


]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image

from autoslug import AutoSlugField
from django.urls import reverse
from django.utils import timezone
from django.db.models.signals import post_save
from django.conf import settings



class Profile(models.Model):
	user = models.OneToOneField(User, on_delete = models.CASCADE)

	image = models.ImageField(default = 'default.jpg', upload_to = 'profile_pics')
	city = models.CharField(max_length=30, blank=True)
	state = models.CharField(max_length=30, blank=True)

	slug = AutoSlugField(populate_from='user')
	bio = models.CharField(max_length=255, blank=True)
	friends = models.ManyToManyField("Profile", blank=True)

	genres = models.CharField(max_length=100, blank=True)

	

	def __str__(self):
		return f'{self.user.username}'

	def get_absolute_url(self):
		return "/accounts/{}".format(self.slug)


	# for image resize and save the updated profile in the database

	def save(self, *args, **kwargs):
		super().save(*args, **kwargs)
		
		img = Image.open(self.image.path)

		if img.height > 300 or img.width > 300:
			output_size = (300, 300)
			img.thumbnail(output_size)
			img.save(self.image.path)


class FriendRequest(models.Model):
	to_user = models.ForeignKey(settings.AUTH_USER_MODEL, 
		related_name='to_user', on_delete=models.CASCADE)
	
	from_user = models.ForeignKey(settings.AUTH_USER_MODEL, 
		related_name='from_user', on_delete=models.CASCADE)

	timestamp = models.DateTimeField(auto_now_add=True)


	def __str__(self):
		return "From {}, to {}".format(self.from_user.username, self.to_user.username)

accounts/forms.py
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User
from . models import Profile


class RegisterForm(UserCreationForm):
	email = forms.EmailField()
	
	class Meta:
		model = User
		fields = ["username", "email", "password1", "password2"]



class UserUpdateForm(forms.ModelForm):
	email = forms.EmailField()
	class Meta:
		model = User
		fields = ["username", "email"]

class ProfileUpdateForm(forms.ModelForm):
	city = forms.CharField()
	state = forms.CharField()
	bio = forms.CharField()

	class Meta:
		model = Profile
		fields = ['image', "city", "state", "bio"]


"""class GenresChoiceForm(forms.Form):
	has_autobiography = forms.BooleanField()
	has_biography = forms.BooleanField()
	has_drama = forms.BooleanField()
	has_fairytale = forms.BooleanField()
	
	

	class Meta:
		model = Genre
		fields = ['has_autobiography', 'has_biography', 'has_drama', 'has_fairytale', 
		'has_fantasy', 'has_folktale'] """

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import RegisterForm, UserUpdateForm, ProfileUpdateForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout

from django.contrib.auth.decorators import login_required
from django.contrib import messages

from .models import Profile, FriendRequest

# add Post model to the feed app

from feed.models import Post
from .forms import RegisterForm, UserUpdateForm, ProfileUpdateForm
from django.contrib.auth import get_user_model
from django.conf import settings
from django.http import HttpResponseRedirect
import random

User = get_user_model()

# Generic view

def signup_view(request):
	if request.method == "POST":
		form = RegisterForm(request.POST)

		if form.is_valid():
			user = form.save()

			# log the user in
			login(request, user)
			# user is directed to his homepage, after successful login
			# return redirect('home:homepage')

			# user is directed to login page after the successful registration
			return redirect('accounts:login')


	else:
		form = RegisterForm()
	
	return render(request, 'accounts/register.html', {'form':form})


def login_view(request):
	if request.method == 'POST':
		form = AuthenticationForm(data=request.POST)
		if form.is_valid():

			#log in the user
			user = form.get_user()
			login(request, user)

			return redirect('accounts:homepage')
	else:
		form = AuthenticationForm()

	return render(request, 'accounts/login.html', {'form':form})


def logout_view(request):
	if request.method == 'POST':
		logout(request)

		# temporary logout direct
		# might create a different logout view

		#return redirect('basic_home/')
		return render(request, 'accounts/logout.html')



# CHANGED ON 11/03
@login_required
def homepage_view(request):

	# Suggest Users is a MESS

	users = Profile.objects.exclude(user = request.user)
	sent_friend_requests = FriendRequest.objects.filter(from_user = request.user)
	sent_to = []
	friends = []
	for user in users:
		friend = user.friends.all()	
		for f in friend:
			if f in friends:
				friend = friend.exclude(user = f.user)
		friends += friend
	my_friends = request.user.profile.friends.all()
	for i in my_friends:
		if i in friends:
			friends.remove(i)
	if request.user.profile in friends:
		friends.remove(request.user.profile)
	random_list = random.sample(list(users), min(len(list(users)), 10))
	for r in random_list:
		if r in friends:
			random_list.remove(r)
	friends += random_list
	for i in my_friends:
		if i in friends:
			friends.remove(i)		
	for sent in sent_friend_requests:
		sent_to.append(sent.to_user)


	# USER'S POST

	"""posts = Post.objects.all().order_by('date_posted')
	user_friends = request.user.profile.friends.all()
	print("FRIENDS :", user_friends)
	display_post = []
	for f in user_friends:
		temp = f.user
		for post in posts:
			temp2 = post.user_name
			if (temp == temp2):
				required_post = Post.objects.filter(user_name=temp2)

				print("POST BY USERS : ", temp2)

				display_post += [temp2]"""
	
	display_post = []
	user_friends = request.user.profile.friends.all()
	for f in user_friends:
		temp = f.user
		posts = Post.objects.filter(user_name=f.user)

		print("POSTS BY :", posts)
		



	print("111111111111111111111", display_post)
	print("222222222222222222", friends)


	all_of = Post.objects.all()
	print("66666666666666666666", all_of)

	print(type(posts))
	print(type(display_post))
	print(type(friends))
	print(type(users))

	context = {
			'users' : friends,
			'sent' : sent_to,
			'posts' : posts

	}
	return render(request, 'accounts/test_homepage.html', context)




###### BEFORE 11/03

"""@login_required
def homepage_view(request):

	# Suggest Users is a MESS

	users = Profile.objects.exclude(user = request.user)
	sent_friend_requests = FriendRequest.objects.filter(from_user = request.user)
	sent_to = []
	friends = []
	for user in users:
		friend = user.friends.all()	
		print(friend)
		for f in friend:
			if f in friends:
				friend = friend.exclude(user = f.user)

		friends += friend

	#print("USERS : ", users)
	#print("1.  ", friends)

	my_friends = request.user.profile.friends.all()
	#print("2.  ", my_friends)

	for i in my_friends:
		if i in friends:
			friends.remove(i)

	if request.user.profile in friends:
		friends.remove(request.user.profile)

	random_list = random.sample(list(users), min(len(list(users)), 10))
	#print("3.  ", random_list)

	for r in random_list:
		if r in friends:
			random_list.remove(r)

	friends += random_list

	#print("4.  ", friends)
	for i in my_friends:
		if i in friends:
			friends.remove(i)

	#print("5.  ", friends)		
	for sent in sent_friend_requests:
		sent_to.append(sent.to_user)

	context = {
			'users' : friends,
			'sent' : sent_to
	}

	#print("6.  ", friends)
	return render(request, 'accounts/test_homepage.html', context)"""


# new genre view
"""@login_required
def genres_view(request):
	context = {}
	form = GenresChoiceForm()
	context['form'] = form

	if request.GET:
		temp1 = request.GET['has_autobiography']
		temp2 = request.GET['has_biography']
		temp3 = request.GET['has_drama']
		temp4 = request.GET['has_fairytale']

		print(temp1)
		print(temp2)
		print(temp3)
		print(temp4)

	return render(request, 'accounts/genres.html', context) """


"""@login_required
def genres_view(request):
	current_user = request.user
	if request.method == "POST":
		if request.POST.get('genres'):
			savedata = current_user.profile
			savedata.genres = request.POST.get('genres')
			savedata.save()
			print("GENRES ARE:", savedata.genres)
			return redirect('accounts:homepage')
	else:
		return render(request, 'accounts/genres.html')"""


@login_required
def genres_view(request):
	current_user = request.user
	existing_genres = current_user.profile.genres
	print("EXISTING GENRES :", existing_genres)

	context = {
			'existing_genres' : existing_genres,
	}
	if request.method == "POST":
		if request.POST.get('genres'):
			savedata = current_user.profile
			savedata.genres = request.POST.get('genres')
			savedata.save()

			return redirect('accounts:homepage')
	else:
	
		return render(request, 'accounts/genres.html', context)

"""@login_required
def homepage_view(request):

	users = Profile.objects.exclude(user = request.user)
	sent_friend_requests = FriendRequest.objects.filter(from_user = request.user)
	sent_to = []
	friends = []
	for user in users:
		friend = user.friends.all()	
		for f in friend:
			if f in friends:
				friend = friend.exclude(user = f.user)

		friends += friend

	my_friends = request.user.profile.friends.all()
	print(my_friends)


	for i in my_friends:
		if i in friends:
			print(i)
			friends.remove(i)
	print("FRIENDS :::::::::::", friends)

	if request.user.profile in friends:
		friends.remove(request.user.profile)

	print("FRIENDS NEW LIST :::::::::::", friends)"""




	# ON USING THESE CODES, SUPERUSER PROFILE IS NOT SHOWN

""" random_list = random.sample(list(users), min(len(list(users)), 10))

	for r in random_list:
		if r in friends:
			random_list.remove(r)

	print("RANDOM :", random_list)

	friends += random_list

	for i in my_friends:
		if i in friends:
			friends.remove(i)

	for sent in sent_friend_requests:
		sent_to.append(sent.to_user)"""

""" context = {
			'users' : friends,
			'sent' : sent_to
	}

	print("USERS are", friends)
	
	return render(request, 'accounts/homepage.html', context)""" 


# recent changes
"""
@login_required
def homepage_view(request):

	users = Profile.objects.exclude(user = request.user)
	print("1")
	print(users)

	friend_count = 0
	logged_in_user_friends = []
	suggested_user_list = []

	sent_friend_requests = FriendRequest.objects.filter(from_user = request.user)
	sent_to = []
	friends = []
	for user in users:
		friend = user.friends.all()	
		print("2")
		print(friend)
		for f in friend:
			if f.user == request.user:
				friend_count = friend_count + 1
				print("3")

				print(user)
				logged_in_user_friends.append(user)

				print("FRIENDS 4444  :::::")
				print(logged_in_user_friends)
	print("5")
	print(friend_count)
	
	for frnd in users:
		for frnds in logged_in_user_friends:
			if frnd != frnds:
				suggested_user_list.append(frnd)

	print("6")
	print(suggested_user_list)


	

	# till here TESTED -------------------

	my_friends = request.user.profile.friends.all()
	print(my_friends)

	for i in my_friends:
		if i in friends:
			friends.remove(i)

	if request.user.profile in friends:
		friends.remove(request.user.profile)

	random_list = random.sample(list(users), min(len(list(users)), 10))

	for r in random_list:
		if r in friends:
			random_list.remove(r)

	friends += random_list

	for i in my_friends:
		if i in friends:
			friends.remove(i)

	for sent in sent_friend_requests:
		sent_to.append(sent.to_user)

	context = {
			'users' : suggested_user_list,
			'friend_count' : friend_count
	}

	
	return render(request, 'accounts/homepage.html', context)"""





 


@login_required
def edit_profile_view(request):
    # return HttpResponse(slug)
    if request.method == "POST":

    	u_form = UserUpdateForm(request.POST, instance=request.user)
    	p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)


    	if u_form.is_valid() and p_form.is_valid():
    		u_form.save()
    		p_form.save()

    		messages.success(request, f'your profile has been updated!')
    		return redirect('accounts:homepage')

    	else:
    		messages.success(request, f'Fill all the fields!')

    else:

	    u_form = UserUpdateForm(instance=request.user)
	    p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
    	'u_form' : u_form,
    	'p_form' : p_form,
    }

    return render(request, 'accounts/edit_profile.html', context)



#------------------------------- currently working on ----------

# users_list view used in the my_profile view

@login_required
def users_list(request):
	
	users = Profile.objects.exclude(user = request.user)

accounts/templates/accounts/login.html
<!DOCTYPE html>
<html>
<head>
	<title>log in or sign up</title>

	<!-- loads the path to your static files -->
    {% load static %}
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0-2/css/all.min.css"> 

	<link rel="stylesheet" type="text/css" href="{% static 'accounts/login_style.css' %}"/> 


	{% load crispy_forms_tags %}

	<style>
        .my-container{
            /*margin-left: 230px;*/
            /*border: 1px solid green; */
           /* max-width: 1280px; */
        }

         
        /*.top-row{
            margin-top: 40px;
            } 

        .my-col{
            border: 1px solid blue;
        }
        
         .my-row{
            border: 1px solid red;
         } */  

        </style> 

</head>
<body>


	<div class="container-fluid my-container">
        
        <div class="row my-row-1 justify-content-center">  

            <div class="col-md-3 my-col top-col my-col-11 ">

            	<div class="login-form">

            		<!--/accounts/login/ -->

					<form class="form-group" action="{% url 'accounts:login' %}" method="post">
						{% csrf_token %}
						{{form|crispy}}


        				<button type="submit" class="btn btn-success btn-lg btn-block"> Sign In</button> 

        				<hr>

        				<p class="text-center"> Don't have an account? Create one</p>

        				<a href="{% url 'accounts:signup' %}" class="btn btn-primary btn-lg btn-block">New Account</a>

					</form>
				</div>


            </div>

        </div>

    </div>


            
	



</body>
</html>

accounts/templates/accounts/logout.html
<!DOCTYPE html>
<html>
<head>
	<title>log out</title>

</head>
<body>
	<h2>You have been logged out!</h2>
       


</body>
</html>

accounts/templates/accounts/register.html
<!DOCTYPE html>
<html>
<head>
	<title>Sign up</title>

	<!-- loads the path to your static files -->
    {% load static %}
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0-2/css/all.min.css"> 

	<link rel="stylesheet" type="text/css" href="{% static 'accounts/register_style.css' %}"/> 

	{% load crispy_forms_tags %}

		<style>
        .my-container{
            /*margin-left: 230px;*/
            /*border: 1px solid green; */
           /* max-width: 1280px; */
        }

         
        /*.top-row{
            margin-top: 40px;
            } 

        .my-col{
            border: 1px solid blue;
        }
        
         .my-row{
            border: 1px solid red;
         }   */

        </style> 

</head>
<body>

	<div class="container-fluid my-container">
        
        <div class="row my-row-1 justify-content-center">  

            <div class="col-md-4 my-col top-col my-col-11 ">

            	<!-- action - submit the information (received via post request) to this url. -->
            	<div class="signup-form">

					<form action="{% url 'accounts:signup' %}" method="POST">
						{% csrf_token %}

						{{form|crispy}} 

						<div class="text-center">
							<button type="submit" class="btn btn-success btn-block"> Sign Up</button>
							<hr>
							<p>Already have an account?</p>
        					<a href="{% url 'accounts:login' %}" class="btn btn-primary btn-block">Sign In</a>
        				</div>
		
					</form>
				</div>
            </div>
        </div>
    </div>

</body>
</html>

accounts/templates/accounts/test_homepage.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}

    {% load crispy_forms_tags %}

    <meta charset="utf-8">

    <title> {{ user.username }}_homepage</title>
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0-2/css/all.min.css">
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" charset="utf-8">      
    </script>

    <link rel="stylesheet" type="text/css" href="{% static 'accounts/test_homepage_style.css' %}"/>

    <style>
        .my-container{
            /*margin-left: 230px;*/
            /*border: 1px solid green; */
           /* max-width: 1280px; */
        }
  
        /*.my-col{
            border: 1px solid blue;
        }
        
         .my-row{
            border: 1px solid red;
         }*/

        </style>

</head>
<body>



  <div class="container-fluid my-container">
        
    <div class="row my-row">        <!-- ROW 1  TITLE  -->
        <div class="col-md-2 my-col top-col my-col-11">


    <div class="wrapper">

        <div class="sidebar">
                        <div class="sidebar-menu">
                            <center class="profile">
                                <img src="{{ user.profile.image.url }}" alt="">
                                <p> {{ user.username }} </p>
                                <hr class="solid">
                            </center>

                            <li class="item">
                                <a href="{% url 'accounts:edit_profile' %}"  class="edit-menu-btn">
                                <i class="fas fa fa-user"></i><span> Edit Profile</span></a>
                            </li>
                            <center> <hr class="solid"> </center>


                            <li class="item">
                                <a href="{% url 'accounts:homepage' %}" class="menu-btn">
                                <i class="fas fa fa-home"></i><span>Home</span>
                                </a>
                            </li>

                            <li class="item">
                                <a href="{% url 'accounts:genres' %}"  class="menu-btn">
                                <i class="fa fa-sticky-note"></i><span>Genres</span></a>
                            </li>

                            <li class="item">
                                <a href="#profile" class="menu-btn">
                                <i class="fas fa fa-book"></i><span>Read List</span></a>
                            </li>

                            <li class="item">
                                <a href="{% url 'accounts:friend_list' %}" class="menu-btn">
                                <i class="fas fa fa-users"></i><span> Friends</span>
                        </a>
                            </li>

                            <li class="item">
                                <a href="{% url 'feed:user-posts' user.username %}" class="menu-btn">
                                <i class="fas fa-newspaper"></i><span>Posts</span></a>
                            </li>

                            <div>
                                <li class="item" id="settings">
                                    <a href="{% url 'feed:post-home' %}" class="last-menu-btn">
                                    <i class="fas fa-cog"></i><span>Settings</span> </a>
                                </li>
                            </div>
                        </div>
                </div> <!-- sidebar end -->

            </div>  <!-- wrapper end -->
            </div>


            <div class="col-md-10 my-col top-col my-col-12 "> <!-- COL 2 -->

                <div class="row my-row">   <!-- ROW 1 --> 


                    <!-- ROW-1 COL 1  TITLE  -->
                    <div class="col-7 my-col top-col my-col-11">  
                        <div class="title top-item"><span>Perusal</span></div>    
                    </div>


                    <!-- ROW-1 COL 2  ADD POST  -->
                        <div class="col-3 my-col top-col my-col-12 text-right"> 
                            <form class="top-item" action="{% url 'feed:post-create' %}" method="post">
                                {% csrf_token %}
                                <button class="btn btn-outline-primary my-2 my-sm-0" type="submit">Create Post</button>
                            </form>
                        </div>

                        <!-- ROW-1 COL 3  LOG - OUT  -->
                        <div class="col-2 my-col top-col my-col-12 text-center"> 
                            <form class="top-item" action="/accounts/logout/" method="post">
                                {% csrf_token %}
                                <button class="btn btn-outline-success my-2 my-sm-0" type="submit"> Logout</button>
                            </form>
                        </div> 




                        


                </div>
               

                <!-- ROW 2   SEARCH BAR  -->
                <div class="row justify-content-center my-row row-2">    
                    <div class="col-6 my-col my-col-21 text-center">
                        <div class="search">
                            <form class="search-form">
                            <input class="search-txt" type="text" name="q" placeholder="search">
                                <a class="search-btn" href="#">
                                <i class="fas fa-search"></i></a>
                            </form>
                        </div>     
                    </div>  
                </div>

    <!-- ############## till here COMMON TEMPLATE FOR ALL THE PAGES  ################# -->

                <!-- ROW 3  READS AND SUGGESTIONS-->
                <div class="row my-row top-row">
                    <div class="col-12 my-col my-col-31">
                        <hr/>
                        <div class="tabs">
                            <input type="radio" name="tabs" id="tabone" checked="checked">
                            <label for="tabone" id="tab-heading-1">Top-Reads</label>
                            <div class="tab">
                                <div class="top-reads">
                                    <div class="card side-card">
                                        <p>Read - 1</p>
                                    </div>
                                    <div class="card side-card">
                                        <p>Read - 2</p>
                                    </div>
                                    <div class="card side-card">
                                        <p>Read - 3</p>
                                    </div>
                                    <div class="card side-card">
                                        <p>Read - 4</p>
                                    </div>
                                </div>
                            </div>
  
                            <input type="radio" name="tabs" id="tabtwo">
                            <label for="tabtwo" id="tab-heading-2">Suggested</label>
                            <div class="tab">
                                <div class="suggested">                                    
                                    {% if users %} 
                                        {% for user_p in users %}
                                            <div class="card side-card">
                                                <a href="{{ user_p.get_absolute_url }}"><img
                                                src="{{ user_p.image.url }}" class="rounded mr-2" width="80" height="80" alt=""/></a>
                                                <a class="text-dark" href="{{ user_p.get_absolute_url }}"><b> {{ user_p }} </b></a>
                                            </div>
                                        {% endfor %}
                                    {% endif %} 
                                </div>                                
                            </div>
  
                        </div>
 
                    </div>              
                </div> <!-- READS AND SUGGESTIONS ROW END -->


                <!-- ROW 4   CONTENT ROW  -->
                <div class="row my-row row-4">    
                    <div class="col-12 my-col my-col-41 ">
                        <hr/>
                        <h4>POSTS</h4> 


                        {% for post in posts %}
                            <div class="card card-signin my-5">
                                <div class="card-body">
                                    <a href="{{ post.user_name.profile.get_absolute_url }}"><img
                                    src="{{ post.user_name.profile.image.url }}"
                                    class="rounded-circle"
                                            width="30" height="30" alt=""/></a>
                                    <a class="text-dark" href="{{ post.user_name.profile.get_absolute_url }}"
                                    ><b>{{ post.user_name }}</b></a>
                                    <br /><small class="text-muted"
                                    >Posted on {{ post.date_posted }}</small>
                                    <br /><br />
                                    <p class="card-text text-dark">{{ post.text_post }}</p>

                                    {% if post.post_image %}
                                        <br />
                                        <img class="card-img-top" src="{{ post.post_image.url }}" width="400" height="500" />
                                        <img src="{{ post.url }}" alt="">

                                    {% endif %}
                                    </div>
                                        {% if post.tags %}
                                            <br />
                                            <p class="text-danger ml-3">
                                            <b>Tags: <i>{{ post.tags }}</i></b>
                                            </p>
                                        {% endif %}
                                
                            </div>
                        {% endfor %}

                        

                        





                    </div>  
                </div>




















        </div> <!-- ROW END -->
    </div>  <!-- CONTAINER END -->











</body>
</html>