accounts/urls.py
from django.conf.urls import url, include
from .import views
from django.urls import path



app_name = 'accounts'

urlpatterns = [
    url(r'^signup/$', views.signup_view, name="signup"),
    url(r'^login/$', views.login_view, name="login"),
    url(r'^logout/$', views.logout_view, name="logout"),
    url(r'^edit_profile/$', views.edit_profile_view, name="edit_profile"),
    #url(r'^my_profile/$', views.my_profile_view, name="my_profile"),

    url(r'^homepage/$', views.homepage_view, name="homepage"),

    url(r'^genres/$', views.genres_view, name="genres"),
    url(r'^friends/$', views.friend_list, name="friend_list"),

    path('friends/friend/delete/<int:id>/', views.delete_friend_using_friends_list, 
    	name='delete_friend'),
    
    #url(r'^friends/delete/<int:id>/$', views.delete_friend, name='delete_friend'),

    #path('friend/delete/<int:id>/', views.delete_friend_visiting_profile, 
	#	name='remove_friend'),


]

feed/urls.py
from django.conf.urls import url, include
from .import views
from django.urls import path
from .views import PostUpdateView, PostListView, UserPostListView

app_name = 'feed'

urlpatterns = [

			url(r'^post/new/$', views.create_post, name='post-create'),
			#url(r'^post/<int:pk>/$', views.post_detail, name='post-detail'),
			path('post/detail', views.post_detail, name='post-detail'),

			#url(r'^user_posts/<str:username>/$', UserPostListView.as_view(), name='user-posts'),
			url(r'^postlist/$', PostListView.as_view(), name='post-home'),
			#path('posts/<slug>/', UserPostListView.as_view(), name='user-posts'),
			path('user_posts/<str:username>', UserPostListView.as_view(), name='user-posts'),


			




]

perusal/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from . import views

from django.conf import settings
from django.conf.urls.static import static

from accounts import views as account_views


 

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'accounts/', include('accounts.urls')),   
    path(r'', views.basic_home_view, name="basic_home"), 
    path('accounts/<slug>/', account_views.profile_view, name='profile_view'),

    path('accounts/friend-request/send/<int:id>/', account_views.send_friend_request, 
    	name='send_friend_request'),

	path('accounts/friend-request/cancel/<int:id>/', account_views.cancel_friend_request, 
		name='cancel_friend_request'),

	path('accounts/friend-request/accept/<int:id>/', account_views.accept_friend_request, 
		name='accept_friend_request'),

	path('accounts/friend-request/delete/<int:id>/', account_views.delete_friend_request, 
		name='delete_friend_request'),

	#path('accounts/friend/delete/<int:id>/', account_views.delete_friend_visiting_profile, 
		#name='remove_friend'),

	path('accounts/friend/delete/<int:id>/', account_views.delete_friend_visiting_profile, 
		name='remove_friend'),

	path(r'feed/', include('feed.urls')),


]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

templates/basic_home.html
<!DOCTYPE html>
<html>
<head>
	<!-- loads the path to your static files -->
    {% load static %}
    <meta charset="UTF-8">
	<title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0-2/css/all.min.css">

	<link rel="stylesheet" type="text/css" href="{% static 'accounts/basic_home_style.css' %}"/> 

    <style>
        .my-container{
            /*margin-left: 230px;*/
            /*border: 1px solid green; */
           /* max-width: 1280px; */
        }

         
        /*.top-row{
            margin-top: 40px;
            }   

        .my-col{
            border: 1px solid blue;
        }
        
         .my-row{
            border: 1px solid red;
         } */

        </style> 

</head>
<body>
    {% csrf_token %}

    <div class="container-fluid my-container">
        
        <div class="row my-row justify-content-center">  

            <div class="col-md-6 my-col top-col my-col-11">
                <h1 class="headertest">
                    Perusal 
                </h1>
            </div>

        </div>


        <div class="row my-row justify-content-center">
            <div class="col-md-12 my-col my-col-21">
                <h3 class="headertestdata">Perusal is a social networking platform designed specially for bibliophiles!</h3>
            </div>
        </div>


        <div class="row my-row justify-content-center">
            <div class="col-md-12 my-col my-col-31">
                <h3 class="headertestdata"> Sign up to discover a whole new world.</h3>
          </div>
        </div>


        <div class="row my-row justify-content-center">
            <div class="col-md-12 my-col my-col-41">
                <h3 class="headertestdata"> If already registered, Sign In.</h3>

            </div>
        </div>


        <div class="row my-row my-row-5 justify-content-center">
            <div class="col-md-3 my-col my-col-51 text-center">
                <a href="{% url 'accounts:login' %}"  class="btn btn-success btn-lg btn-lg"> &nbsp&nbsp&nbspSign &nbspIn&nbsp&nbsp&nbsp</a> 
            </div>

            <div class="col-md-3 my-col my-col-52 text-center">
                <a href="{% url 'accounts:signup' %}" class="btn btn-primary btn-lg btn-lg">New Account</a>

            </div>
        </div>
    </div>



	

<!--header menu end-->
       
    <!--main container start-->

        <!-- <div class="main-container">
    
            <div class="login-form">
                <div class="form-group ">
                    <input type="text" class="form-control" placeholder="Username " id="UserName">
                    <i class="fas fa-user"></i>
                </div>

                <div class="form-group log-status">
                    <input type="password" class="form-control" placeholder="Password" id="Passwod">
                    <i class="fas fa-lock"></i>
                </div>

                <span class="alert">Invalid Credentials</span>
                <a class="link" href="#">Lost your password?</a>
      
                <button type="button" class="log-btn"> Sign In </button>
                <hr>
                <h3> or </h3>
                <button type="button" class="sign-btn"> Sign Up </button>
     
    
            </div> -->

    <!--main container end-->
        </div> 
</div>


</body>
</html>